### ISSUE TITLE
IntranetUserJS: Generate PIN codes

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-generate-pin#1]
Luo määritetyille asiakastyypeille nelinumeroiset PIN-koodit salasanaksi.

Testaus:

Poista intranetUserJS-asetuksesta käytöstä skripti "Generoi salasanan mainituille asiakastyypeille  nelinumeroiseksi".

Määrittele pluginiin asiakastyypit, joille pitää generoida nelinumeroinen salasana.
Aktivoi plugin.

Vaihda salasana määritetylle/määritetyille asiakastyypeille.

**Comment by lmstrand** [comment]
Seuranta kimpoista, joissa otettu käyttöön nexteillä. Kommentoi tikettiä, kun määritetty omassa kimpassa:

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by Kati-Helle** [comment]
Helle-nextissä määrittelin liitännäiseen tarvittavat asiakastyypit ja aktivoin liitännäisen.

Testasin liitännäiseen määritellyistä asiakastyypeistä kolmella asiakastyypillä. Vaihda salasana -toiminnolla Pin-koodiksi muodostui 8-merkkinen arvo. Arvossa numeroita ja kirjaimia.

**Comment by lmstrand** [comment]
pluginin rimpsusta puuttui paluufunktio jonka takia tuo ei näköjään toiminut oikein. Vein korjauksen nexteille ja nyt näyttäisi toimivan, kun testasin LAPSI ja EASIAKAS-tyypeille generointia helle-nextillä.

**Comment by Kati-Helle** [comment]
Kiitos korjauksesta. Testasin Helle-nextissä kaikkien liitännäiseen määriteltyjen asiakastyyppien salasana-generoinnin asiakkaan Vaihda salasana -toiminnossa. Oikein toimii.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu, toimii.

**Comment by atarnus** [comment]
Outi-nextillä toimii. 

Huomiona, että ensin syötin asiakastyypit sinne välilyöntien kanssa, ja vain ensimmäinen silloin toimi. Sittemmin poistin välilyönnit, ja alkoi kaikki syötetyt toimimaan.

**Comment by ElinaUotila** [comment]
Kirkes-nextillä otettu käyttöön ja toimii.

**Comment by ReettaSiili** [comment]
Toimii Siilin nextillä kaikilla määritellyillä asiakastyypeillä.

**Comment by lmstrand** [comment]
Kiitos testeistä.

**Comment by lmstrand** [comment]
> Outi-nextillä toimii.
> 
> Huomiona, että ensin syötin asiakastyypit sinne välilyöntien kanssa, ja vain ensimmäinen silloin toimi. Sittemmin poistin välilyönnit, ja alkoi kaikki syötetyt toimimaan.

Aika jännä. Tuolla on kyllä välilyöntien poisto ennenkuin arvot pistetään arrayhyn pilkku erottimena.

**Comment by LeenaKinnunen** [comment]
Lapissakin toimii nextillä asiakaslajeilla HENKILO,KOTIPALVEL,LAPSI,LAOMATOIMI,YHTEISO.
Asiakaslajille HUOLLETTAV,KIRJASTO tulee teksti "Koha ei voi näyttää vanhaa salasanaa. Jätä salasanakentät tyhjäksi jos et halua vaihtaa salasanaa." jos painaa Vaihda salasanaa.

**Comment by Tuomas-Kyyti** [comment]
Kyytin peukku oli toinen noista "2 more" eli tämä ok.

**Comment by LastuJanneS** [comment]
Lastun nextillä myös määritykset tehty ja otettu käyttöön.

**Comment by AnneliO** [comment]
Tämä on kaikilla kunnossa, joten suljen tiketin.
